# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./ClientApp/
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./ClientApp/
        run: npm test
    - run: npm run build --prod --output-path docs --base-href=href="https://se491-softwareengineeringstudio.github.io/Mindful/"
    #--base-href="https://se491-softwareengineeringstudio.github.io/Mindful/"
    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        FOLDER : ./ClientApp/dist
        branch: gh-pages
        github_token : ${{ secrets.GITHUB_TOKEN }}  
